language: generic 
services:
    - docker

before_install:
    - docker build -t client -f ./client/Dockerfile.dev ./client
    - docker build -t apitests .

script:
    - docker run -e CI=true client npm run test
    - docker run apitests

after_success:
    - docker build -t scootay237/client ./client
    - docker build -t scootay237/api ./api
    - docker build -t scootay237/nginx ./nginx
    # log into docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # push images to docker hub
    - docker push scootay237/client
    - docker push scootay237/api
    - docker push scootay237/nginx

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "webapp-multi-container"
    env: "WebappMultiContainer-env"
    bucket_name: "elasticbeanstalk-us-east-2-027835436621"
    bucket_path: "multi-container-webapp"
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY