FROM mcr.microsoft.com/dotnet/core/sdk:3.0-alpine AS build
WORKDIR /app

COPY api.sln .
COPY api/api.csproj ./api/
COPY tests/tests.csproj ./tests/
RUN dotnet restore

COPY ./api .
COPY ./tests .

RUN dotnet build api.sln

FROM build as tests
WORKDIR /app/tests/S3ServiceTests
RUN dotnet test --verbosity=normal
