version: '3.7'

services:
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            -   /app/node_modules
            -   ./client:/app
        stdin_open: true
    api:
        build:
            context: ./api
            dockerfile: Dockerfile
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports: 
            - '4000:80'